/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationResponseDTO { 
    id?: number;
    serviceRequestId?: number;
    serviceTitle?: string;
    workerProfileId?: number;
    workerFullName?: string;
    workerCity?: string;
    workerExperienceLevel?: string;
    workerHourlyRate?: number;
    workerProfilePhotoUrl?: string;
    workerCategories?: Array<ApplicationResponseDTO.WorkerCategoriesEnum>;
    coverLetter?: string;
    proposedRate?: number;
    status?: ApplicationResponseDTO.StatusEnum;
    appliedAt?: string;
}
export namespace ApplicationResponseDTO {
    export const WorkerCategoriesEnum = {
        Plumbing: 'PLUMBING',
        Electricity: 'ELECTRICITY',
        Cleaning: 'CLEANING',
        Painting: 'PAINTING',
        Carpentry: 'CARPENTRY',
        Moving: 'MOVING',
        Gardening: 'GARDENING',
        AcRepair: 'AC_REPAIR',
        ApplianceRepair: 'APPLIANCE_REPAIR',
        Security: 'SECURITY',
        Design: 'DESIGN',
        WebDevelopment: 'WEB_DEVELOPMENT',
        MobileDevelopment: 'MOBILE_DEVELOPMENT'
    } as const;
    export type WorkerCategoriesEnum = typeof WorkerCategoriesEnum[keyof typeof WorkerCategoriesEnum];
    export const StatusEnum = {
        Pending: 'PENDING',
        Shortlisted: 'SHORTLISTED',
        Accepted: 'ACCEPTED',
        Rejected: 'REJECTED',
        Withdrawn: 'WITHDRAWN'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


