/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceResponseDTO { 
    id?: number;
    title?: string;
    description?: string;
    budget?: number;
    category?: string;
    city?: string;
    status?: string;
    createdAt?: string;
    clientUsername?: string;
    clientFirstName?: string;
    imageIds?: Array<number>;
}

