export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './authController.serviceInterface';
export * from './clientController.service';
import { ClientControllerService } from './clientController.service';
export * from './clientController.serviceInterface';
export * from './imageController.service';
import { ImageControllerService } from './imageController.service';
export * from './imageController.serviceInterface';
export * from './serviceRequestController.service';
import { ServiceRequestControllerService } from './serviceRequestController.service';
export * from './serviceRequestController.serviceInterface';
export * from './testController.service';
import { TestControllerService } from './testController.service';
export * from './testController.serviceInterface';
export * from './workerApplicationController.service';
import { WorkerApplicationControllerService } from './workerApplicationController.service';
export * from './workerApplicationController.serviceInterface';
export const APIS = [AuthControllerService, ClientControllerService, ImageControllerService, ServiceRequestControllerService, TestControllerService, WorkerApplicationControllerService];
