/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginRequestDTO } from '../model/models';
import { LoginResponseDTO } from '../model/models';
import { RegisterRequestDTO } from '../model/models';
import { RegisterResponseDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/auth/login
     * @param loginRequestDTO 
     */
    login(loginRequestDTO: LoginRequestDTO, extraHttpRequestParams?: any): Observable<LoginResponseDTO>;

    /**
     * 
     * 
     * @endpoint post /api/auth/logout
     * @param refreshToken 
     */
    logout(refreshToken?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/auth/refresh
     * @param refreshToken 
     */
    refresh(refreshToken?: string, extraHttpRequestParams?: any): Observable<LoginResponseDTO>;

    /**
     * 
     * 
     * @endpoint post /api/auth/register/client
     * @param registerRequestDTO 
     */
    registerClient(registerRequestDTO: RegisterRequestDTO, extraHttpRequestParams?: any): Observable<RegisterResponseDTO>;

    /**
     * 
     * 
     * @endpoint post /api/auth/register/worker
     * @param data 
     * @param diplomaFiles 
     * @param certificateFiles 
     */
    registerWorker(data: string, diplomaFiles?: Array<Blob>, certificateFiles?: Array<Blob>, extraHttpRequestParams?: any): Observable<RegisterResponseDTO>;

}
