/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApplicationResponseDTO } from '../model/models';
import { ServiceResponseDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ClientControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/client/services/{serviceId}/applications/{applicationId}/accept
     * @param serviceId 
     * @param applicationId 
     */
    acceptApplication(serviceId: number, applicationId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/client/services/{id}/cancel
     * @param id 
     */
    cancelService(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/client/services/create
     * @param data 
     * @param images 
     */
    create(data: string, images?: Array<Blob>, extraHttpRequestParams?: any): Observable<ServiceResponseDTO>;

    /**
     * 
     * 
     * @endpoint post /api/client/services/{serviceId}/applications
     * @param serviceId 
     */
    getApplications(serviceId: number, extraHttpRequestParams?: any): Observable<Array<ApplicationResponseDTO>>;

    /**
     * 
     * 
     * @endpoint get /api/client/services
     */
    getMyServices(extraHttpRequestParams?: any): Observable<Array<ServiceResponseDTO>>;

    /**
     * 
     * 
     * @endpoint patch /api/client/services/{serviceId}/applications/{applicationId}/reject
     * @param serviceId 
     * @param applicationId 
     */
    rejectApplication(serviceId: number, applicationId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint patch /api/client/services/{serviceId}/applications/{applicationId}/shortlist
     * @param serviceId 
     * @param applicationId 
     */
    shortlist(serviceId: number, applicationId: number, extraHttpRequestParams?: any): Observable<{}>;

}
