/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ServiceResponseDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ServiceRequestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/services/browse
     * @param category 
     * @param city 
     */
    browse(category?: 'PLUMBING' | 'ELECTRICITY' | 'CLEANING' | 'PAINTING' | 'CARPENTRY' | 'MOVING' | 'GARDENING' | 'AC_REPAIR' | 'APPLIANCE_REPAIR' | 'SECURITY' | 'DESIGN' | 'WEB_DEVELOPMENT' | 'MOBILE_DEVELOPMENT', city?: string, extraHttpRequestParams?: any): Observable<Array<ServiceResponseDTO>>;

    /**
     * 
     * 
     * @endpoint get /api/services/{id}
     * @param id 
     */
    get(id: number, extraHttpRequestParams?: any): Observable<ServiceResponseDTO>;

}
